In [35]:
import numpy as np
from math import exp
from random import seed
from random import random
X=np.array(([2,9],[1,5],[3,6],[5,4]),dtype=float)
Y=np.array(([92],[85],[89],[90]),dtype=float)
y=Y/100

In [36]:
m,n=np.shape(Y)
print(m)
print(n)
print(X)
print(y)

4
1
[[2. 9.]
 [1. 5.]
 [3. 6.]
 [5. 4.]]
[[0.92]
 [0.85]
 [0.89]
 [0.9 ]]


In [37]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [38]:
def derivative_sigmoid(x):
    return x*(1-x)

In [39]:
epoch=1000000
lr=0.1
inputlayer_neurons=2
hiddenlayer_neurons=3
output_neurons=1

In [40]:
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [41]:
print(wh)
print(bh)
print(wout)
print(bout)

[[0.62644724 0.3813545  0.7994029 ]
 [0.93192885 0.76244388 0.21871742]]
[[0.86226754 0.99505756 0.49765372]]
[[0.15822913]
 [0.39899297]
 [0.03549744]]
[[0.33243913]]


In [42]:
for i in range(epoch):
    h_ip=np.dot(X,wh)+bh
    h_act=sigmoid(h_ip)
    o_ip=np.dot(h_act,wout)+bout
    output=sigmoid(o_ip)
    eo=y-output
    outgrad=derivative_sigmoid(output)
    d_output=eo*outgrad
    eh=d_output.dot(wout.T)
    hiddengrad=derivative_sigmoid(h_act)
    d_hidden=eh*hiddengrad
    wout+=h_act.T.dot(d_output)*lr
    wh+=X.T.dot(d_hidden)*lr

In [43]:
print(wh)

[[0.70795231 0.13000085 0.14328648]
 [1.38251458 0.12433765 0.13789342]]


In [44]:
print(wout)

[[-4.61009422]
 [ 2.07597678]
 [ 5.37272968]]


In [45]:
print("Normalized input: \n"+str(X))
print("Actual output: \n"+str(y))
print("Predicted output: \n",output)

Normalized input: 
[[2. 9.]
 [1. 5.]
 [3. 6.]
 [5. 4.]]
Actual output: 
[[0.92]
 [0.85]
 [0.89]
 [0.9 ]]
Predicted output: 
 [[0.91434775]
 [0.85073981]
 [0.89647924]
 [0.89737072]]
